/**
 * Drop #3 patient sprites — FULL state machinery (M75).
 *
 * 13 character archetypes ported with their 5 states (stable +
 * triaged + deteriorating + arrested + post-resus). Self-contained
 * PAL + renderer so chars do not collide with sprites.ts (Williams
 * M44 uses E/J/K/y differently; M72 uses 0-9 for Stan/Patel/Chloe
 * clothing; the drop uses 1-9/E/J/K/x/y/z for these patients).
 *
 * Wired into PATIENT_SPRITES via the per-case map in sprites.ts.
 */

export interface SpriteDiff {
  row: number;
  col: number;
  ch: string;
}

export interface PatientStateRecipe {
  /** Which base frame the state recipe operates on. */
  base: "upright" | "supine";
  /** Optional skin-tint substitution map applied before diffs. */
  skinMap?: Record<string, string>;
  /** Per-cell overrides applied on top of the (possibly substituted) base. */
  diffs?: SpriteDiff[];
}

export interface PatientSpriteBlueprint {
  upright: string[];
  exhale: string[];
  supine: string[];
  states: Record<string, PatientStateRecipe>;
}

const DROP_PAL: Record<string, string | null> = {
  '#': '#1a1310',
  '.': null,
  '0': '#3a1b22',
  '1': '#2a2e36',
  '2': '#3e4450',
  '3': '#5e6470',
  '4': '#dc6090',
  '5': '#f49ec0',
  '6': '#ffc4dc',
  '7': '#4FA3A0',
  '8': '#4a3a68',
  '9': '#7d6da0',
  'A': '#a4d4e8',
  'B': '#5a6a8a',
  'C': '#b5a59a',
  'D': '#f0ebdc',
  'E': '#b0a3cc',
  'F': '#e87a72',
  'G': '#ffd2c8',
  'H': '#6e4a2e',
  'I': '#dcc46a',
  'J': '#dcc46a',
  'K': '#f0dc8a',
  'L': '#f6dcc2',
  'M': '#7c6e74',
  'N': '#c8b9bb',
  'O': '#a04050',
  'P': '#c7416f',
  'Q': '#e472a0',
  'R': '#f49ec0',
  'S': '#ecbf9f',
  'T': '#7a92a8',
  'U': '#d04848',
  'V': '#9aaccd',
  'W': '#e8e4d8',
  'X': '#f4f7f9',
  'Y': '#cfc9b8',
  'Z': '#5a5a5a',
  'a': '#e0f0f8',
  'b': '#7e8eae',
  'c': '#d2c4b8',
  'd': '#e6dccf',
  'e': '#0d0a08',
  'f': '#f29991',
  'g': '#fbbab2',
  'h': '#4a3220',
  'i': '#f0dc8a',
  'j': '#8a5e3a',
  'k': '#2a1c10',
  'l': '#fff0dc',
  'm': '#9a8a8e',
  'n': '#b5a4a6',
  'o': '#7a2030',
  'p': '#8a2548',
  'q': '#5e2030',
  'r': '#f29991',
  's': '#c99680',
  't': '#b2c0ce',
  'u': '#e8786a',
  'v': '#b6c4dd',
  'w': '#f0e8d8',
  'x': '#a85a3a',
  'y': '#5e7080',
  'z': '#7A1E16',
  '~': '#3a2a22',
};

export const DROP_PATIENT_SPRITES: Record<string, PatientSpriteBlueprint> = {
  ahmed: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkhhhhhhhk......',
      '.......kkhhgggggHhk.....',
      '.......khgggsssssHk.....',
      '.......khssSSSSSSsk.....',
      '.......khsSLLLLLLSk.....',
      '.......hSSLLLLLLLLS.....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLL~~LLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOLLSSk....',
      '........hSSSSSSSSk......',
      '........hsssssssh.......',
      '.........SSSSSk.........',
      '.........11111..........',
      '........1133311.........',
      '.......11233332111......',
      '......112222222211......',
      '.....11222222222211.....',
      '....1122222333222211....',
      '....122222233332221.....',
      '....122222333332221.....',
      '....122223333322221.....',
      '....122222222222221.....',
      '....122222222222221.....',
      '....122222222222221.....',
      '....111111111111111.....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkhhhhhhhk......',
      '.......kkhhgggggHhk.....',
      '.......khgggsssssHk.....',
      '.......khssSSSSSSsk.....',
      '.......khsSLLLLLLSk.....',
      '.......hSSLLLLLLLLS.....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLL~~LLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOLLSSk....',
      '........hSSSSSSSSk......',
      '........hsssssssh.......',
      '.........SSSSSk.........',
      '.........11111..........',
      '........1133311.........',
      '.......11233332111......',
      '......112222222211......',
      '......11222222222211....',
      '.....1122222333222211...',
      '....122222233332221.....',
      '....122222333332221.....',
      '....122223333322221.....',
      '....122222222222221.....',
      '....122222222222221.....',
      '....122222222222221.....',
      '....111111111111111.....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........kkhhhhhhhk...',
      '..........kkhhgggggHhk..',
      '..........khgggsssssHk..',
      '..........khssSSSSSSsk..',
      '.........khsSLLLLLLSSk..',
      '........kSSLL~~~~LLSSk..',
      '........hSSLLLLLLLLSSk..',
      '........hSSLLLLLLLLSSk..',
      '........hSSLLLeeLLLSSk..',
      '........hSSLLqqqqLLSSk..',
      '........hSSLLqqqqLLSSk..',
      '.........hSSSSSSSSSSk...',
      '..........hsssssssh.....',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 14, col: 11, ch: 'O' }, { row: 14, col: 12, ch: 'O' }, { row: 14, col: 13, ch: 'O' }, { row: 9, col: 10, ch: 'k' }, { row: 9, col: 16, ch: 'k' }, { row: 23, col: 10, ch: 'S' }, { row: 23, col: 11, ch: 'L' }, { row: 23, col: 12, ch: 'L' }, { row: 23, col: 13, ch: 'S' }, { row: 24, col: 9, ch: 's' }, { row: 24, col: 10, ch: 'S' }, { row: 24, col: 11, ch: 'L' }, { row: 24, col: 12, ch: 'S' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 7, col: 17, ch: 'A' }, { row: 8, col: 17, ch: 'a' }, { row: 9, col: 10, ch: 'k' }, { row: 9, col: 16, ch: 'k' }, { row: 14, col: 10, ch: 'O' }, { row: 14, col: 11, ch: 'q' }, { row: 14, col: 12, ch: 'q' }, { row: 14, col: 13, ch: 'q' }, { row: 14, col: 14, ch: 'O' }, { row: 22, col: 8, ch: 'S' }, { row: 22, col: 9, ch: 'L' }, { row: 22, col: 10, ch: 'L' }, { row: 22, col: 11, ch: 'L' }, { row: 22, col: 12, ch: 'S' }, { row: 23, col: 7, ch: 's' }, { row: 23, col: 8, ch: 'S' }, { row: 23, col: 9, ch: 'L' }, { row: 23, col: 10, ch: 'L' }, { row: 23, col: 11, ch: 'L' }, { row: 23, col: 12, ch: 'L' }, { row: 23, col: 13, ch: 'S' }, { row: 24, col: 8, ch: 's' }, { row: 24, col: 9, ch: 'S' }, { row: 24, col: 10, ch: 'S' }, { row: 24, col: 11, ch: 'S' }, { row: 24, col: 12, ch: 's' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 12, col: 12, ch: 'T' }, { row: 12, col: 13, ch: 'T' }, { row: 12, col: 14, ch: 'T' }, { row: 12, col: 15, ch: 'T' }, { row: 13, col: 15, ch: 'T' }, { row: 13, col: 16, ch: 't' }, { row: 17, col: 12, ch: 'Z' }, { row: 18, col: 12, ch: 'Z' }, { row: 19, col: 13, ch: 'Z' }],
      },
    },
  },
  connor: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkkkkkkkk.......',
      '........kssssssss.......',
      '.......khSSSSSSSSk......',
      '.......khSLLLLLLLSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hSSSSSSSSh......',
      '.........SSSSk..........',
      '........yyyyyyyy........',
      '.......yy##yy##yyy......',
      '......yyyyyyyyyyyyy.....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkkkkkkkk.......',
      '........kssssssss.......',
      '.......khSSSSSSSSk......',
      '.......khSLLLLLLLSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hSSSSSSSSh......',
      '.........SSSSk..........',
      '........yyyyyyyy........',
      '.......yy##yy##yyy......',
      '......yyyyyyyyyyyyy.....',
      '.....yyyyyyyyyyyyyyy....',
      '......yyyyyyyyyyyyyy....',
      '......yyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........kkkkkkkkk....',
      '...........kssssssss....',
      '..........khSSSSSSSSk...',
      '..........khSLLLLLLLSk..',
      '..........hSSLLLLLLLSk..',
      '.........hSSLL~~LLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSh....',
      '..........yyyyyyyy......',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 8, col: 12, ch: '~' }, { row: 8, col: 14, ch: '~' }, { row: 12, col: 11, ch: 'q' }, { row: 12, col: 12, ch: 'q' }, { row: 12, col: 13, ch: 'q' }, { row: 12, col: 14, ch: 'q' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
        diffs: [{ row: 8, col: 11, ch: 'w' }, { row: 8, col: 12, ch: 'w' }, { row: 8, col: 13, ch: 'e' }, { row: 8, col: 14, ch: 'w' }, { row: 8, col: 15, ch: 'w' }, { row: 12, col: 11, ch: 'b' }, { row: 12, col: 12, ch: 'b' }, { row: 12, col: 13, ch: 'b' }, { row: 12, col: 14, ch: 'b' }, { row: 13, col: 12, ch: 'q' }, { row: 13, col: 13, ch: 'q' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 10, col: 13, ch: 'T' }, { row: 10, col: 14, ch: 't' }, { row: 11, col: 12, ch: 'Z' }, { row: 11, col: 13, ch: 'Z' }, { row: 11, col: 14, ch: 'Z' }, { row: 11, col: 15, ch: 'Z' }],
      },
    },
  },
  doherty: {
    upright: [
      '........................',
      '........................',
      '..........GGGG..........',
      '.........GggggG.........',
      '........GgggggggG.......',
      '........GgggggggG.......',
      '........#gggggg#........',
      '........#sssssss#.......',
      '.......ksSSSSSSSSk......',
      '.......ksSLL~LLLLSk.....',
      '.......ksSLLLLLLLSk.....',
      '.......ksSLwewewLSk.....',
      '.......ksSLLLLLLLSk.....',
      '.......ksSLLLeLLLSk.....',
      '.......ksSLL~~LLLSk.....',
      '.......ksSLLOOLLLSk.....',
      '........kSSSSSSSSk......',
      '........hssssssh........',
      '.........SSSSk..........',
      '........8EEEEEEE8.......',
      '.......889999999988.....',
      '......88999999999988....',
      '.....88999EEEEEE99988...',
      '....88999EEEEEEEE99988..',
      '....899EEEEEEEEEEEE998..',
      '....8999EEEEEEEEEE9998..',
      '....89999EEEEEEEE99998..',
      '....899999EEEEEE999998..',
      '....8999999999999999998.',
      '....8888888888888888888.',
      '........................',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '..........GGGG..........',
      '.........GggggG.........',
      '........GgggggggG.......',
      '........GgggggggG.......',
      '........#gggggg#........',
      '........#sssssss#.......',
      '.......ksSSSSSSSSk......',
      '.......ksSLL~LLLLSk.....',
      '.......ksSLLLLLLLSk.....',
      '.......ksSLwewewLSk.....',
      '.......ksSLLLLLLLSk.....',
      '.......ksSLLLeLLLSk.....',
      '.......ksSLL~~LLLSk.....',
      '.......ksSLLOOLLLSk.....',
      '........kSSSSSSSSk......',
      '........hssssssh........',
      '.........SSSSk..........',
      '........8EEEEEEE8.......',
      '.......889999999988.....',
      '......88999999999988....',
      '......88999EEEEEE99988..',
      '.....88999EEEEEEEE99988.',
      '....899EEEEEEEEEEEE998..',
      '....8999EEEEEEEEEE9998..',
      '....89999EEEEEEEE99998..',
      '....899999EEEEEE999998..',
      '....8999999999999999998.',
      '....8888888888888888888.',
      '........................',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '..............GGGG......',
      '............GgggggG.....',
      '...........GggggggggG...',
      '...........#gggggg#.....',
      '...........#sssssss#....',
      '..........ksSSSSSSSSk...',
      '.........ksSLL~~LLLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLeeLLSk...',
      '.........ksSLLqqqqLSk...',
      '..........ksSSSSSSSk....',
      '...........hsssssh......',
      '..........WWWWWWWWW.....',
      '.........WWWWWWWWWWW....',
      '........WWWWWWWWWWWWW...',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WYWYWYWYWYWYWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 11, col: 12, ch: '~' }, { row: 11, col: 14, ch: '~' }, { row: 15, col: 12, ch: 'q' }, { row: 15, col: 13, ch: 'q' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
        diffs: [{ row: 11, col: 11, ch: 'J' }, { row: 11, col: 15, ch: 'J' }, { row: 14, col: 11, ch: 'K' }, { row: 14, col: 15, ch: 'K' }, { row: 11, col: 12, ch: '~' }, { row: 11, col: 13, ch: '~' }, { row: 11, col: 14, ch: '~' }, { row: 15, col: 11, ch: 'q' }, { row: 15, col: 12, ch: 'q' }, { row: 15, col: 13, ch: 'q' }, { row: 15, col: 14, ch: 'q' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 12, col: 13, ch: 'T' }, { row: 12, col: 14, ch: 'T' }, { row: 12, col: 15, ch: 'T' }, { row: 12, col: 16, ch: 't' }, { row: 11, col: 14, ch: 'Z' }, { row: 11, col: 15, ch: 'Z' }, { row: 16, col: 13, ch: 'Z' }, { row: 17, col: 13, ch: 'Z' }, { row: 8, col: 14, ch: 'K' }, { row: 9, col: 14, ch: 'K' }],
      },
    },
  },
  jake: {
    upright: [
      '........................',
      '........................',
      '.........hhh.hhh........',
      '........hhhhkhhhk.......',
      '.......kWWWWWWWWWk......',
      '.......kWWzzzWWWWk......',
      '.......kWWzzzzzWWk......',
      '.......kWWWWWWWWWk......',
      '.......khSSSSSSSSk......',
      '.......khSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOLLSk.....',
      '........hSSSSSSSSh......',
      '.......ccccccccccc......',
      '......cccccccccccc......',
      '......cdddddddddddc.....',
      '.......kkkkkkkkk........',
      '......kkkk...kkkkkk.....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkzzkkkkkkk....',
      '.....kkkkkkzzzkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........hhh.hhh........',
      '........hhhhkhhhk.......',
      '.......kWWWWWWWWWk......',
      '.......kWWzzzWWWWk......',
      '.......kWWzzzzzWWk......',
      '.......kWWWWWWWWWk......',
      '.......khSSSSSSSSk......',
      '.......khSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOLLSk.....',
      '........hSSSSSSSSh......',
      '.......ccccccccccc......',
      '......cccccccccccc......',
      '......cdddddddddddc.....',
      '.......kkkkkkkkk........',
      '......kkkk...kkkkkk.....',
      '......kkkkkkkkkkkkkk....',
      '......kkkkkkkkkkkkkk....',
      '.....kkkkkkzzkkkkkkk....',
      '.....kkkkkkzzzkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhh.hhh.....',
      '...........hhhhkhhhk....',
      '..........kWWWWWWWWWk...',
      '..........kWWzzzWWWWk...',
      '..........kWWzzzzzWWk...',
      '..........kWWWWWWWWWk...',
      '..........khSSSSSSSSk...',
      '.........khSLL~~LLSSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSh....',
      '.........ccccccccccc....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWzzWWWWWWWWW..',
      '.....WWWWWWzzzWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 9, col: 10, ch: 'k' }, { row: 9, col: 16, ch: 'k' }, { row: 14, col: 11, ch: 'q' }, { row: 14, col: 12, ch: 'q' }, { row: 14, col: 13, ch: 'q' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 5, col: 10, ch: 'z' }, { row: 5, col: 14, ch: 'z' }, { row: 6, col: 10, ch: 'z' }, { row: 6, col: 14, ch: 'z' }, { row: 7, col: 11, ch: 'z' }, { row: 7, col: 13, ch: 'z' }, { row: 9, col: 12, ch: '~' }, { row: 9, col: 14, ch: '~' }, { row: 14, col: 11, ch: 'b' }, { row: 14, col: 12, ch: 'b' }, { row: 14, col: 13, ch: 'b' }, { row: 18, col: 14, ch: 'z' }, { row: 19, col: 14, ch: 'z' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 13, col: 11, ch: 'T' }, { row: 13, col: 12, ch: 'T' }, { row: 13, col: 13, ch: 'T' }, { row: 13, col: 14, ch: 'T' }, { row: 13, col: 15, ch: 't' }, { row: 15, col: 16, ch: 'T' }, { row: 16, col: 16, ch: 'T' }],
      },
    },
  },
  joan: {
    upright: [
      '........................',
      '........................',
      '.........GGGGGG.........',
      '........GGggggGGG.......',
      '.......GgggggggggG......',
      '.......#gggggg#.........',
      '.......#sssssss#........',
      '......ksSSSSSSSSk.......',
      '......ksSLLLLLLLSk......',
      '......ksSLwewewLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSL~~~LLLSk......',
      '......ksSLLLeLLLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSLLOOOLLSk......',
      '.......hsssssssh........',
      '........SSSSk...........',
      '.......vVVVVVVVv........',
      '......vVVVVVVVVVv.......',
      '.....vVVVVVVVVVVVv......',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVV##V####VVVVv.....',
      '....vVVV##VV####VVv.....',
      '....vVVV#VV###VVVVv.....',
      '....vVVVV#####VVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vvvvvvvvvvvvvvv.....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........GGGGGG.........',
      '........GGggggGGG.......',
      '.......GgggggggggG......',
      '.......#gggggg#.........',
      '.......#sssssss#........',
      '......ksSSSSSSSSk.......',
      '......ksSLLLLLLLSk......',
      '......ksSLwewewLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSL~~~LLLSk......',
      '......ksSLLLeLLLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSLLOOOLLSk......',
      '.......hsssssssh........',
      '........SSSSk...........',
      '.......vVVVVVVVv........',
      '......vVVVVVVVVVv.......',
      '.....vVVVVVVVVVVVv......',
      '.....vVVVVVVVVVVVVVv....',
      '.....vVVVVVVVVVVVVVv....',
      '....vVV##V####VVVVv.....',
      '....vVVV##VV####VVv.....',
      '....vVVV#VV###VVVVv.....',
      '....vVVVV#####VVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vvvvvvvvvvvvvvv.....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '..............GGGGGG....',
      '............GGggggGGG...',
      '...........GgggggggggG..',
      '...........#gggggg#.....',
      '...........#sssssss#....',
      '..........ksSSSSSSSSk...',
      '..........ksSLL~~LLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLeeLLSk...',
      '.........ksSLqqqqqLSk...',
      '..........ksSSSSSSSk....',
      '...........hsssssh......',
      '..........WWWWWWWWW.....',
      '.........WWWWWWWWWWW....',
      '........WWWWWWWWWWWWW...',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WYWYWYWYWYWYWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
        diffs: [{ row: 9, col: 11, ch: '~' }, { row: 9, col: 15, ch: '~' }, { row: 14, col: 11, ch: 'q' }, { row: 14, col: 12, ch: 'q' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
        diffs: [{ row: 9, col: 11, ch: '~' }, { row: 9, col: 12, ch: '~' }, { row: 9, col: 13, ch: '~' }, { row: 9, col: 14, ch: '~' }, { row: 9, col: 15, ch: '~' }, { row: 14, col: 11, ch: 'B' }, { row: 14, col: 12, ch: 'B' }, { row: 14, col: 13, ch: 'B' }, { row: 14, col: 14, ch: 'B' }, { row: 27, col: 5, ch: 'V' }, { row: 27, col: 17, ch: 'V' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 12, col: 13, ch: 'T' }, { row: 12, col: 14, ch: 'T' }, { row: 12, col: 15, ch: 'T' }, { row: 12, col: 16, ch: 't' }, { row: 23, col: 6, ch: 'T' }, { row: 24, col: 6, ch: 'T' }],
      },
    },
  },
  leo: {
    upright: [
      '........................',
      '........................',
      '........................',
      '........................',
      '..........hhhh..........',
      '.........hHHHHhh........',
      '........hhHHHHHHh.......',
      '........hhssssssh.......',
      '........hSSSSSSSk.......',
      '.......hSSLLLLLLSk......',
      '.......hSSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOLLSk.....',
      '........hSSSSSSSk.......',
      '.........hssssh.........',
      '..........SSSk..........',
      '.........VVVVVV.........',
      '........VVVVVVVVV.......',
      '.......VVVVViVVVVVV.....',
      '......VVViVVVVVViVVV....',
      '......VVVVVVVVVVVVVV....',
      '......VVVVViVVVVVVVV....',
      '......VVVVVVVVVViVVV....',
      '......VVViVVVVVVVVVV....',
      '......VVVVVVVVVVVVVV....',
      '......VVVVVVVVVVVVVV....',
      '.......BB........BB.....',
      '.......BB........BB.....',
      '........................',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '........................',
      '........................',
      '..........hhhh..........',
      '.........hHHHHhh........',
      '........hhHHHHHHh.......',
      '........hhssssssh.......',
      '........hSSSSSSSk.......',
      '.......hSSLLLLLLSk......',
      '.......hSSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOLLSk.....',
      '........hSSSSSSSk.......',
      '.........hssssh.........',
      '..........SSSk..........',
      '.........VVVVVV.........',
      '........VVVVVVVVV.......',
      '.......VVVVViVVVVVV.....',
      '.......VVViVVVVVViVVV...',
      '.......VVVVVVVVVVVVVV...',
      '......VVVVViVVVVVVVV....',
      '......VVVVVVVVVViVVV....',
      '......VVViVVVVVVVVVV....',
      '......VVVVVVVVVVVVVV....',
      '......VVVVVVVVVVVVVV....',
      '.......BB........BB.....',
      '.......BB........BB.....',
      '........................',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '..............hhhh......',
      '............hHHHHhh.....',
      '...........hhHHHHHHh....',
      '..........hhssssssh.....',
      '..........hSSSSSSSk.....',
      '..........hSSLLLLLSk....',
      '.........hSSL~~~~LSk....',
      '.........hSSLLLLLLSk....',
      '.........hSSLLLeeLSk....',
      '.........hSSLqqqLLSk....',
      '..........hSSSSSSSk.....',
      '...........hssssh.......',
      '..........VVVVVVVV......',
      '.........VVVVViVVVV.....',
      '.........WWWWWWWWWW.....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WYWYWYWYWYWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '.........WWWWWWWWWW.....',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 14, col: 11, ch: 'o' }, { row: 14, col: 12, ch: 'O' }, { row: 14, col: 13, ch: 'O' }, { row: 14, col: 14, ch: 'o' }, { row: 11, col: 16, ch: 'A' }, { row: 12, col: 16, ch: 'a' }],
      },
      deteriorating: {
        base: 'upright',
        diffs: [{ row: 10, col: 11, ch: 'w' }, { row: 10, col: 12, ch: 'w' }, { row: 10, col: 13, ch: 'w' }, { row: 10, col: 14, ch: 'w' }, { row: 10, col: 15, ch: 'w' }, { row: 14, col: 11, ch: 'W' }, { row: 14, col: 12, ch: 'W' }, { row: 14, col: 13, ch: 'W' }, { row: 14, col: 14, ch: 'W' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 11, col: 14, ch: 'T' }, { row: 11, col: 15, ch: 't' }, { row: 15, col: 13, ch: 'Z' }, { row: 16, col: 13, ch: 'Z' }],
      },
    },
  },
  liam: {
    upright: [
      '........................',
      '........................',
      '.........hhhhhhh........',
      '........hhhHHhhhh.......',
      '.......khhHHHHhhhh......',
      '.......khhhsssssH.......',
      '.......khssSSSSSSk......',
      '.......khSSLLLLLSk......',
      '.......hSSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOOLSk.....',
      '........hsssssssh.......',
      '........kkkkkkkk........',
      '.........SSSSk..........',
      '........kkkkkkkk........',
      '.......kkkkkkkkkkk......',
      '......kkkkkkkkkkkkk.....',
      '.....kkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkkk...',
      '....kkSSkkkkkkkkSSkk....',
      '....kkSSSSkkkkSSSSkk....',
      '....kkkSSSSSSSSSSkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........hhhhhhh........',
      '........hhhHHhhhh.......',
      '.......khhHHHHhhhh......',
      '.......khhhsssssH.......',
      '.......khssSSSSSSk......',
      '.......khSSLLLLLSk......',
      '.......hSSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOOLSk.....',
      '........hsssssssh.......',
      '........kkkkkkkk........',
      '.........SSSSk..........',
      '........kkkkkkkk........',
      '.......kkkkkkkkkkk......',
      '......kkkkkkkkkkkkk.....',
      '......kkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkkk...',
      '....kkSSkkkkkkkkSSkk....',
      '....kkSSSSkkkkSSSSkk....',
      '....kkkSSSSSSSSSSkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhhhhhh.....',
      '...........hhhHHhhhh....',
      '..........khhHHHHhhhh...',
      '..........khhhsssssH....',
      '..........khssSSSSSSk...',
      '..........khSSLLLLLSk...',
      '.........hSSLL~~LLSSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hsssssssh.....',
      '..........kkkkkkkkk.....',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 5, col: 16, ch: 'A' }, { row: 6, col: 16, ch: 'a' }, { row: 8, col: 11, ch: 'k' }, { row: 8, col: 16, ch: 'k' }, { row: 12, col: 11, ch: 'O' }, { row: 12, col: 12, ch: 'r' }, { row: 12, col: 13, ch: 'O' }, { row: 12, col: 14, ch: 'r' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 8, col: 11, ch: '~' }, { row: 8, col: 12, ch: '~' }, { row: 8, col: 13, ch: '~' }, { row: 8, col: 14, ch: '~' }, { row: 8, col: 15, ch: '~' }, { row: 8, col: 16, ch: '~' }, { row: 12, col: 11, ch: 'q' }, { row: 12, col: 12, ch: 'q' }, { row: 12, col: 13, ch: 'q' }, { row: 12, col: 14, ch: 'q' }, { row: 13, col: 12, ch: 'b' }, { row: 13, col: 13, ch: 'b' }, { row: 21, col: 6, ch: 'k' }, { row: 21, col: 7, ch: 'k' }, { row: 21, col: 16, ch: 'k' }, { row: 21, col: 17, ch: 'k' }, { row: 22, col: 6, ch: 'k' }, { row: 22, col: 7, ch: 'k' }, { row: 22, col: 8, ch: 'k' }, { row: 22, col: 9, ch: 'k' }, { row: 22, col: 14, ch: 'k' }, { row: 22, col: 15, ch: 'k' }, { row: 22, col: 16, ch: 'k' }, { row: 22, col: 17, ch: 'k' }, { row: 23, col: 7, ch: 'k' }, { row: 23, col: 8, ch: 'k' }, { row: 23, col: 9, ch: 'k' }, { row: 23, col: 10, ch: 'k' }, { row: 23, col: 11, ch: 'k' }, { row: 23, col: 12, ch: 'k' }, { row: 23, col: 13, ch: 'k' }, { row: 23, col: 14, ch: 'k' }, { row: 23, col: 15, ch: 'k' }, { row: 23, col: 16, ch: 'k' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 12, col: 13, ch: 'T' }, { row: 12, col: 14, ch: 'T' }, { row: 12, col: 15, ch: 'T' }, { row: 12, col: 16, ch: 't' }, { row: 20, col: 6, ch: 'T' }, { row: 21, col: 6, ch: 'T' }, { row: 20, col: 19, ch: 'T' }, { row: 21, col: 19, ch: 'T' }],
      },
    },
  },
  marcus: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkkkkkkkk.......',
      '........kkkkkkkkk.......',
      '.......kkssssssssk......',
      '.......khSSSSSSSSk......',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hSSSSSSSSh......',
      '.........SSSSk..........',
      '........WWWWWWWWW.......',
      '.......WWWWWWWWWWW......',
      '......WWWWWWWWWWWWW.....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWzzWWWWWWWWWW....',
      '.....WWzzzzWWWWWWWWW....',
      '.....WWzzzzWWWWWWWWW....',
      '.....WWWzzWWWWWWWWWW....',
      '.....WWzWWWWWWWWWWWW....',
      '.....WzWWWWWWWWWWWWW....',
      '.....zWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkkkkkkkk.......',
      '........kkkkkkkkk.......',
      '.......kkssssssssk......',
      '.......khSSSSSSSSk......',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hSSSSSSSSh......',
      '.........SSSSk..........',
      '........WWWWWWWWW.......',
      '.......WWWWWWWWWWW......',
      '......WWWWWWWWWWWWW.....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '.....WWWzzWWWWWWWWWW....',
      '.....WWzzzzWWWWWWWWW....',
      '.....WWzzzzWWWWWWWWW....',
      '.....WWWzzWWWWWWWWWW....',
      '.....WWzWWWWWWWWWWWW....',
      '.....WzWWWWWWWWWWWWW....',
      '.....zWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '.....WWWWWWWWWWWWWWW....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........kkkkkkkkk....',
      '...........kkkkkkkkk....',
      '..........kkssssssssk...',
      '..........khSSSSSSSSk...',
      '..........hSSLLLLLLLSk..',
      '.........hSSLL~~LLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSh....',
      '..........WWWWWWWW......',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWzzzWWWWWWWWW...',
      '.....WWzzzzzzzWWWWWWW...',
      '.....WzzzzzzzzzWWWWWW...',
      '.....WzzzzzzzzzWWWWWW...',
      '.....WWzzzzzzzWWWWWWW...',
      '.....WWWzzzzzWWWWWWWW...',
      '.....WWWWzzzWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 21, col: 9, ch: 'S' }, { row: 21, col: 10, ch: 'L' }, { row: 22, col: 9, ch: 'S' }, { row: 22, col: 10, ch: 'L' }, { row: 8, col: 11, ch: 'k' }, { row: 8, col: 16, ch: 'k' }],
      },
      deteriorating: {
        // BT 17 R3 deferred-finding-1 — Marcus's deteriorating recipe
        // was carrying pallor + leg marks but no facial cue, so a
        // severe-DKA Marcus looked the same as a triaged Marcus apart
        // from skin tone. Replicating Leo's drowsy/Kussmaul pattern
        // (closed eyes at the eye row, open-mouth dark gap at the
        // mouth row) — both are textbook signs of advanced DKA in an
        // adult presentation.
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [
          // existing pallor / leg z-marks preserved (artist intent)
          { row: 20, col: 8, ch: 'z' }, { row: 20, col: 9, ch: 'z' }, { row: 20, col: 10, ch: 'z' }, { row: 20, col: 11, ch: 'z' }, { row: 20, col: 12, ch: 'z' },
          { row: 21, col: 8, ch: 'z' }, { row: 21, col: 9, ch: 'z' }, { row: 21, col: 10, ch: 'z' }, { row: 21, col: 11, ch: 'z' }, { row: 21, col: 12, ch: 'z' }, { row: 21, col: 13, ch: 'z' },
          { row: 22, col: 9, ch: 'z' }, { row: 22, col: 10, ch: 'z' }, { row: 22, col: 11, ch: 'z' }, { row: 22, col: 12, ch: 'z' }, { row: 22, col: 13, ch: 'z' },
          { row: 23, col: 10, ch: 'z' }, { row: 24, col: 9, ch: 'z' }, { row: 25, col: 8, ch: 'z' }, { row: 26, col: 7, ch: 'z' }, { row: 27, col: 8, ch: 'z' }, { row: 28, col: 9, ch: 'z' },
          // new: drowsy closed eyes — row 8 cols 12 & 14 are the
          // pupils in `wewew`. Replacing the black `e` with the
          // skin-toned `S` (which the skinMap above remaps to `c`)
          // produces closed eyelids on top of pale skin.
          { row: 8, col: 12, ch: 'S' }, { row: 8, col: 14, ch: 'S' },
          // new: open mouth Kussmaul — row 12 cols 12-15 are the
          // mouth `OOOO`. Pale lips (`d`) plus a darker `o` gap in
          // the middle reads as parted, breathing-heavily mouth.
          { row: 12, col: 11, ch: 'd' }, { row: 12, col: 12, ch: 'd' },
          { row: 12, col: 13, ch: 'o' }, { row: 12, col: 14, ch: 'o' },
          { row: 12, col: 15, ch: 'd' },
        ],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 11, col: 12, ch: 'T' }, { row: 11, col: 13, ch: 'T' }, { row: 11, col: 14, ch: 'T' }, { row: 11, col: 15, ch: 'T' }, { row: 11, col: 16, ch: 't' }, { row: 19, col: 19, ch: 'T' }, { row: 20, col: 19, ch: 'T' }, { row: 21, col: 19, ch: 'T' }],
      },
    },
  },
  maya: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........khhhhhhhhk......',
      '........khhhhhhhhk......',
      '........khhsssssHk......',
      '........khsSSSSSSk......',
      '........khSLLLLLSk......',
      '.......khSLwewewLSk.....',
      '.......khSL~~~~~LSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOLLLSk....',
      '........hSSSSSSSSk......',
      '.........hssssh.........',
      '.........SSSSk..........',
      '........yyyyyyyy........',
      '.......yy##yy##yyy......',
      '......yyyyyyyyyyyyy.....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........khhhhhhhhk......',
      '........khhhhhhhhk......',
      '........khhsssssHk......',
      '........khsSSSSSSk......',
      '........khSLLLLLSk......',
      '.......khSLwewewLSk.....',
      '.......khSL~~~~~LSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOLLLSk....',
      '........hSSSSSSSSk......',
      '.........hssssh.........',
      '.........SSSSk..........',
      '........yyyyyyyy........',
      '.......yy##yy##yyy......',
      '......yyyyyyyyyyyyy.....',
      '......yyyyyyyyyyyyyy....',
      '......yyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........khhhhhhhhk...',
      '..........khhhhhhhhhk...',
      '..........khhssssssHk...',
      '..........khsSSSSSSSk...',
      '..........khSLL~~LLSk...',
      '.........khSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSk....',
      '...........hssssssh.....',
      '..........WWWWWWWWWW....',
      '.........WWWWWWWWWWWW...',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WYWYWYWYWYWYWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '.........WWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 9, col: 11, ch: '~' }, { row: 9, col: 16, ch: '~' }, { row: 14, col: 12, ch: 'O' }, { row: 14, col: 14, ch: 'O' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 7, col: 11, ch: 'k' }, { row: 7, col: 12, ch: 'k' }, { row: 7, col: 13, ch: 'k' }, { row: 7, col: 14, ch: 'k' }, { row: 7, col: 15, ch: 'k' }, { row: 7, col: 16, ch: 'k' }, { row: 10, col: 12, ch: '~' }, { row: 10, col: 13, ch: '~' }, { row: 10, col: 14, ch: '~' }, { row: 10, col: 15, ch: '~' }, { row: 14, col: 11, ch: 'o' }, { row: 14, col: 12, ch: 'O' }, { row: 14, col: 13, ch: 'o' }, { row: 14, col: 14, ch: 'O' }, { row: 14, col: 15, ch: 'o' }, { row: 15, col: 12, ch: 'q' }, { row: 15, col: 13, ch: 'q' }, { row: 15, col: 14, ch: 'q' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 12, col: 13, ch: 'T' }, { row: 12, col: 14, ch: 'T' }, { row: 12, col: 15, ch: 'T' }, { row: 12, col: 16, ch: 't' }, { row: 16, col: 19, ch: 'T' }, { row: 17, col: 19, ch: 'T' }],
      },
    },
  },
  ravi: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........khhgggggk.......',
      '........khhgggggk.......',
      '........khggsssss.......',
      '........khssSSSSSk......',
      '.......khSSLLLLLSk......',
      '.......khSLwewewLSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLL~~LLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLTLLLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hsssssssh.......',
      '........tttttttttt......',
      '.........SSSSk..........',
      '.........hhhhh..........',
      '........hHHHHHHh........',
      '.......hHWWWWWWWHh......',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHHHHHHHHHHHHh....',
      '......hhhhhhhhhhhhhh....',
      '......hhhhhhhhhhhhhh....',
      '......hhhhhhhhhhhhhh....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........khhgggggk.......',
      '........khhgggggk.......',
      '........khggsssss.......',
      '........khssSSSSSk......',
      '.......khSSLLLLLSk......',
      '.......khSLwewewLSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLL~~LLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLTLLLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hsssssssh.......',
      '........tttttttttt......',
      '.........SSSSk..........',
      '.........hhhhh..........',
      '........hHHHHHHh........',
      '.......hHWWWWWWWHh......',
      '.......hHWWWWWWWWWHh....',
      '.......hHWWWWWWWWWHh....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHHHHHHHHHHHHh....',
      '......hhhhhhhhhhhhhh....',
      '......hhhhhhhhhhhhhh....',
      '......hhhhhhhhhhhhhh....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........khhgggggk....',
      '..........khhgggggk.....',
      '..........khggsssss.....',
      '..........khssSSSSSk....',
      '.........khSSLLLLLSk....',
      '.........khSL~~~~LSk....',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLLqqqLLSk...',
      '..........hssssssssh....',
      '..........WWWWWWWWWW....',
      '.........WWWWWWWWWWWW...',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WYWYWYWYWYWYWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '.........WWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 14, col: 11, ch: 'O' }, { row: 14, col: 12, ch: 'r' }, { row: 14, col: 13, ch: 'r' }, { row: 14, col: 14, ch: 'O' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
        diffs: [{ row: 14, col: 11, ch: 'b' }, { row: 14, col: 12, ch: 'B' }, { row: 14, col: 13, ch: 'B' }, { row: 14, col: 14, ch: 'b' }, { row: 17, col: 8, ch: 'B' }, { row: 17, col: 13, ch: 'B' }, { row: 23, col: 5, ch: 'V' }, { row: 23, col: 16, ch: 'V' }, { row: 8, col: 11, ch: 'k' }, { row: 8, col: 16, ch: 'k' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 10, col: 11, ch: 'Z' }, { row: 10, col: 12, ch: 'Z' }, { row: 10, col: 13, ch: 'Z' }, { row: 10, col: 14, ch: 'Z' }, { row: 10, col: 15, ch: 'Z' }, { row: 10, col: 16, ch: 'Z' }, { row: 11, col: 10, ch: 'Z' }, { row: 11, col: 11, ch: 'b' }, { row: 11, col: 12, ch: 'b' }, { row: 11, col: 13, ch: 'b' }, { row: 11, col: 14, ch: 'b' }, { row: 11, col: 15, ch: 'b' }, { row: 11, col: 16, ch: 'b' }, { row: 11, col: 17, ch: 'Z' }, { row: 12, col: 10, ch: 'Z' }, { row: 12, col: 11, ch: 'b' }, { row: 12, col: 12, ch: 'b' }, { row: 12, col: 13, ch: 'b' }, { row: 12, col: 14, ch: 'b' }, { row: 12, col: 15, ch: 'b' }, { row: 12, col: 16, ch: 'b' }, { row: 12, col: 17, ch: 'Z' }, { row: 13, col: 11, ch: 'Z' }, { row: 13, col: 12, ch: 'Z' }, { row: 13, col: 13, ch: 'Z' }, { row: 13, col: 14, ch: 'Z' }, { row: 13, col: 15, ch: 'Z' }, { row: 13, col: 16, ch: 'Z' }, { row: 12, col: 9, ch: 'T' }, { row: 13, col: 9, ch: 'T' }],
      },
    },
  },
  ruby: {
    upright: [
      '........................',
      '........................',
      '........................',
      '..........kkkk..........',
      '.........khhhhhk........',
      '........khhhHHhhk.......',
      '........khhHHHHhk7......',
      '.......khhsssssHk7......',
      '.......kSSSSSSSSk.......',
      '.......kSLLLLLLLSk......',
      '......ksSLwewewLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSLLLeLLLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSSLOOLSSk.......',
      '.......kssssssh.........',
      '.........SSSk...........',
      '........466666664.......',
      '.......455555555554.....',
      '......4555X555X5555.....',
      '.....455555X5555555.....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....44444444444444.....',
      '......WWW......WWW......',
      '.....WWWW......WWWW.....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '........................',
      '..........kkkk..........',
      '.........khhhhhk........',
      '........khhhHHhhk.......',
      '........khhHHHHhk7......',
      '.......khhsssssHk7......',
      '.......kSSSSSSSSk.......',
      '.......kSLLLLLLLSk......',
      '......ksSLwewewLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSLLLeLLLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSSLOOLSSk.......',
      '.......kssssssh.........',
      '.........SSSk...........',
      '........466666664.......',
      '.......455555555554.....',
      '......4555X555X5555.....',
      '.....455555X5555555.....',
      '......4555555X5555554...',
      '......4555555X5555554...',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....44444444444444.....',
      '......WWW......WWW......',
      '.....WWWW......WWWW.....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkk........',
      '...........khhhhhk......',
      '..........khhhHHhhk.....',
      '..........khhHHHHhk.....',
      '.........khhsssssHk.....',
      '.........kSSSSSSSSk.....',
      '.........kSLL~~LLSk.....',
      '........ksSLLLLLLSk.....',
      '........ksSLLeeLLSk.....',
      '........ksSLqqqqLSk.....',
      '.........kssssssh.......',
      '.........WWWWWWWW.......',
      '........WWWWWWWWWW......',
      '.......WWWWWWWWWWWW.....',
      '......WWWWWWWWWWWWWW....',
      '......WYWYWYWYWYWYWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '.......WWWWWWWWWWWW.....',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 10, col: 10, ch: 'e' }, { row: 10, col: 14, ch: 'e' }, { row: 14, col: 10, ch: 'o' }, { row: 14, col: 11, ch: 'O' }, { row: 14, col: 12, ch: 'O' }, { row: 14, col: 13, ch: 'o' }],
      },
      deteriorating: {
        base: 'upright',
        diffs: [{ row: 14, col: 11, ch: 'b' }, { row: 14, col: 12, ch: 'b' }, { row: 12, col: 11, ch: 'k' }, { row: 12, col: 13, ch: 'k' }, { row: 16, col: 10, ch: 'B' }, { row: 16, col: 13, ch: 'B' }, { row: 17, col: 7, ch: '.' }, { row: 17, col: 8, ch: '.' }, { row: 17, col: 15, ch: '.' }, { row: 17, col: 16, ch: '.' }, { row: 27, col: 4, ch: 'V' }, { row: 27, col: 5, ch: 'V' }, { row: 27, col: 18, ch: 'V' }, { row: 27, col: 19, ch: 'V' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "B", "S": "b", "L": "V", "l": "v"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 11, col: 11, ch: 'T' }, { row: 11, col: 12, ch: 'T' }, { row: 11, col: 13, ch: 't' }, { row: 17, col: 11, ch: 'Z' }, { row: 18, col: 12, ch: 'Z' }],
      },
    },
  },
  sarah: {
    upright: [
      '........................',
      '........................',
      '..........hhhh..........',
      '.........hhhhhhk........',
      '........hhhHHhhhhk......',
      '........hhhHHHHhhhk.....',
      '........khhsssssHhk.....',
      '........khSSSSSSSHk.....',
      '.......khSLLLLLLLSHk....',
      '.......khSLwewewLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLLeLLLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLOOLLLLSk....',
      '........hSSSSSSSSk......',
      '.......hhssssssshh......',
      '.......hhhSSSShhhh......',
      '......XXXWWWWWWWXXX.....',
      '.....XXXWWWWWWWWWXXXX...',
      '....XXWWWWWWWWWWWWWXX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XYYYWWWWWWWYYYYYX...',
      '....XXXXXXXXXXXXXXXXX...',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '..........hhhh..........',
      '.........hhhhhhk........',
      '........hhhHHhhhhk......',
      '........hhhHHHHhhhk.....',
      '........khhsssssHhk.....',
      '........khSSSSSSSHk.....',
      '.......khSLLLLLLLSHk....',
      '.......khSLwewewLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLLeLLLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLOOLLLLSk....',
      '........hSSSSSSSSk......',
      '.......hhssssssshh......',
      '.......hhhSSSShhhh......',
      '......XXXWWWWWWWXXX.....',
      '.....XXXWWWWWWWWWXXXX...',
      '....XXWWWWWWWWWWWWWXX...',
      '.....XXWWWWWWWWWWWWWXX..',
      '.....XWWWWWWWWWWWWWWWX..',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XYYYWWWWWWWYYYYYX...',
      '....XXXXXXXXXXXXXXXXX...',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhhh........',
      '...........hhhhhhk......',
      '..........hhhHHhhhhk....',
      '..........hhhHHHHhhhk...',
      '..........khhsssssHhk...',
      '..........khSSSSSSSHk...',
      '.........khSLL~~LLLSk...',
      '.........hhSLLLLLLLSk...',
      '.........hhSLLLLLLLSk...',
      '.........hhSLLLeeLLSk...',
      '.........hhSLqqqqLLSk...',
      '..........hSSSSSSSk.....',
      '.........hhsssssshh.....',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWzzzWWWWWWWW..',
      '.....WWWWWzzzzzWWWWWWW..',
      '.....WWWWzzzzzzzWWWWWW..',
      '.....WWWWWzzzzzWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 9, col: 12, ch: '~' }, { row: 9, col: 14, ch: '~' }, { row: 14, col: 12, ch: 'O' }, { row: 14, col: 13, ch: 'O' }],
      },
      deteriorating: {
        base: 'upright',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 9, col: 12, ch: 'w' }, { row: 9, col: 14, ch: 'w' }, { row: 9, col: 13, ch: 'w' }, { row: 14, col: 12, ch: 'd' }, { row: 14, col: 13, ch: 'd' }, { row: 29, col: 8, ch: 'z' }, { row: 29, col: 9, ch: 'z' }, { row: 29, col: 10, ch: 'z' }, { row: 29, col: 11, ch: 'z' }, { row: 29, col: 12, ch: 'z' }, { row: 29, col: 13, ch: 'z' }, { row: 29, col: 14, ch: 'z' }, { row: 29, col: 15, ch: 'z' }, { row: 29, col: 16, ch: 'z' }, { row: 29, col: 17, ch: 'z' }, { row: 28, col: 11, ch: 'z' }, { row: 28, col: 13, ch: 'z' }, { row: 28, col: 15, ch: 'z' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        skinMap: {"s": "C", "S": "c", "L": "d", "l": "D"},
        diffs: [{ row: 12, col: 13, ch: 'T' }, { row: 12, col: 14, ch: 'T' }, { row: 12, col: 15, ch: 'T' }, { row: 12, col: 16, ch: 't' }, { row: 17, col: 19, ch: 'T' }, { row: 18, col: 19, ch: 'T' }],
      },
    },
  },
  tom: {
    upright: [
      '........................',
      '........................',
      '.........hhhhhhh........',
      '........hHhhhhhHh.......',
      '.......hhHhhgggHhh......',
      '.......khhgggsssHk......',
      '.......khssSSSSSSk......',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hsssssssh.......',
      '........kkkkkkkkk.......',
      '.........SSSSk..........',
      '.........WWWWW..........',
      '........kWWWWWkk........',
      '.......kkWWWWWWkkk......',
      '......kkkWWWWWWWkkk.....',
      '.....kkkhWWWWWWWhkkk....',
      '.....kkhhWWWWWWWhhkk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkkkkkkkkkkkkkk....',
      '........................',
    ],
    exhale: [
      '........................',
      '........................',
      '.........hhhhhhh........',
      '........hHhhhhhHh.......',
      '.......hhHhhgggHhh......',
      '.......khhgggsssHk......',
      '.......khssSSSSSSk......',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hsssssssh.......',
      '........kkkkkkkkk.......',
      '.........SSSSk..........',
      '.........WWWWW..........',
      '........kWWWWWkk........',
      '.......kkWWWWWWkkk......',
      '......kkkWWWWWWWkkk.....',
      '.....kkkhWWWWWWWhkkk....',
      '......kkhhWWWWWWWhhkk...',
      '......kkhhhhhhhhhhhhk...',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkkkkkkkkkkkkkk....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhhhhhh.....',
      '...........hHhhhhhHh....',
      '..........hhHhhgggHhh...',
      '..........khhgggsssHk...',
      '..........khssSSSSSSk...',
      '..........hSSLLLLLLSk...',
      '.........hSSLL~~LLSSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqLLSk...',
      '..........hssssssh......',
      '..........kkkkkkkk......',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
    states: {
      triaged: {
        base: 'upright',
        diffs: [{ row: 8, col: 11, ch: '~' }, { row: 8, col: 16, ch: '~' }, { row: 12, col: 11, ch: 'O' }, { row: 12, col: 14, ch: 'O' }],
      },
      deteriorating: {
        base: 'upright',
        diffs: [{ row: 12, col: 11, ch: 'z' }, { row: 12, col: 12, ch: 'z' }, { row: 12, col: 13, ch: 'z' }, { row: 12, col: 14, ch: 'z' }, { row: 13, col: 12, ch: 'z' }, { row: 13, col: 13, ch: 'z' }, { row: 14, col: 13, ch: 'z' }, { row: 15, col: 13, ch: 'z' }, { row: 16, col: 12, ch: 'z' }, { row: 16, col: 13, ch: 'z' }, { row: 17, col: 11, ch: 'z' }, { row: 17, col: 12, ch: 'z' }, { row: 17, col: 13, ch: 'z' }, { row: 17, col: 14, ch: 'z' }, { row: 7, col: 17, ch: 'A' }, { row: 8, col: 17, ch: 'a' }],
      },
      arrested: {
        base: 'supine',
        skinMap: {"s": "M", "S": "m", "L": "n", "l": "N"},
      },
      postResus: {
        base: 'supine',
        diffs: [{ row: 11, col: 12, ch: 'T' }, { row: 11, col: 13, ch: 'T' }, { row: 11, col: 14, ch: 'T' }, { row: 11, col: 15, ch: 'T' }, { row: 11, col: 16, ch: 't' }, { row: 10, col: 14, ch: 'Z' }, { row: 10, col: 15, ch: 'Z' }, { row: 8, col: 13, ch: 'I' }, { row: 8, col: 14, ch: 'I' }],
      },
    },
  },
};

function substSkin(rows: string[], map: Record<string, string>): string[] {
  return rows.map((row) => {
    let out = "";
    for (let i = 0; i < row.length; i++) {
      out += map[row[i]!] ?? row[i];
    }
    return out;
  });
}

function applyDiffs(rows: string[], diffs: SpriteDiff[]): string[] {
  const grid = rows.map((r) => r.split(""));
  for (const d of diffs) {
    if (grid[d.row] && d.col < grid[d.row]!.length) {
      grid[d.row]![d.col] = d.ch;
    }
  }
  return grid.map((r) => r.join(""));
}

export function dropPatientFrames(patientId: string, state: string): string[][] | null {
  const bp = DROP_PATIENT_SPRITES[patientId];
  if (!bp) return null;
  // Stable is the base upright + exhale
  if (state === "stable" || state === "unseen" || state === "discharged") {
    return [bp.upright, bp.exhale];
  }
  const stateKey = state === "post_resus" || state === "admitted" ? "postResus" : state === "deceased" ? "arrested" : state;
  const recipe = bp.states[stateKey];
  if (!recipe) return null;
  const baseInhale = recipe.base === "supine" ? bp.supine : bp.upright;
  const baseExhale = recipe.base === "supine" ? bp.supine : bp.exhale;
  const tinted1 = recipe.skinMap ? substSkin(baseInhale, recipe.skinMap) : baseInhale;
  const tinted2 = recipe.skinMap ? substSkin(baseExhale, recipe.skinMap) : baseExhale;
  const f1 = recipe.diffs ? applyDiffs(tinted1, recipe.diffs) : tinted1;
  const f2 = recipe.diffs ? applyDiffs(tinted2, recipe.diffs) : tinted2;
  // Supine states are single-frame (no exhale variant needed)
  return recipe.base === "supine" ? [f1] : [f1, f2];
}

export function dropFrameToSvg(rows: string[], scale = 6): string {
  const w = rows[0]!.length;
  const h = rows.length;
  let svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" ` +
    `shape-rendering="crispEdges" style="image-rendering:pixelated;` +
    `width:${w * scale}px;height:${h * scale}px;display:block">`;
  for (let y = 0; y < h; y++) {
    const row = rows[y]!;
    let x = 0;
    while (x < row.length) {
      const ch = row[x]!;
      const col = DROP_PAL[ch];
      if (col == null) {
        x++;
        continue;
      }
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      svg += `<rect x="${x}" y="${y}" width="${end - x}" height="1" fill="${col}"/>`;
      x = end;
    }
  }
  svg += "</svg>";
  return svg;
}