/**
 * Extra patient sprite archetypes (M65) — 13 characters from drop #3.
 *
 * These are character DESIGNS, not 1:1 mappings to authored cases:
 *   ahmed (58M anterior STEMI) != case_acute_heart_failure_ahmed
 *     (Yusuf Ahmed · 78M · acute heart failure).
 *   sarah (32F postpartum haemorrhage) != case_ectopic_minors_sarah
 *     (Sarah Hassan · 31F · ruptured ectopic).
 *   marcus (26M penetrating chest stab) != case_dka_marcus
 *     (Marcus Brooks · 19M · DKA).
 *
 * Stored here as a registry for the Asset Library to render and
 * for future case authoring to map onto. NOT wired into
 * PATIENT_SPRITES — that would render the wrong character on each
 * shift. Coverage stays Beth + Williams (2/17) until design
 * authors targeted sprites or content authors new cases.
 *
 * Palette is self-contained (own PAL + renderer) so chars used
 * differently from sprites.ts (E/J/K in particular) do not collide.
 */

const EXTRA_PATIENT_PAL: Record<string, string | null> = {
  '#': '#1a1310',
  '.': null,
  '0': '#3a1b22',
  '1': '#2a2e36',
  '2': '#3e4450',
  '3': '#5e6470',
  '4': '#dc6090',
  '5': '#f49ec0',
  '6': '#ffc4dc',
  '7': '#4FA3A0',
  '8': '#4a3a68',
  '9': '#7d6da0',
  'B': '#5a6a8a',
  'C': '#b5a59a',
  'D': '#f0ebdc',
  'E': '#b0a3cc',
  'H': '#6e4a2e',
  'J': '#dcc46a',
  'K': '#f0dc8a',
  'L': '#f6dcc2',
  'M': '#7c6e74',
  'N': '#c8b9bb',
  'O': '#a04050',
  'S': '#ecbf9f',
  'T': '#7a92a8',
  'V': '#9aaccd',
  'W': '#e8e4d8',
  'X': '#f4f7f9',
  'Y': '#cfc9b8',
  'Z': '#5a5a5a',
  'b': '#7e8eae',
  'c': '#d2c4b8',
  'd': '#e6dccf',
  'e': '#0d0a08',
  'g': '#9c9a93',
  'h': '#4a3220',
  'k': '#2a1c10',
  'l': '#fff0dc',
  'm': '#9a8a8e',
  'n': '#b5a4a6',
  'o': '#7a2030',
  'q': '#5e2030',
  's': '#c99680',
  't': '#b2c0ce',
  'v': '#b6c4dd',
  'w': '#f0e8d8',
  'x': '#a85a3a',
  'y': '#5e7080',
  'z': '#7A1E16',
  '~': '#3a2a22',
};

export const EXTRA_PATIENT_SPRITES: Record<string, Record<string, string[]>> = {
  ahmed: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkhhhhhhhk......',
      '.......kkhhgggggHhk.....',
      '.......khgggsssssHk.....',
      '.......khssSSSSSSsk.....',
      '.......khsSLLLLLLSk.....',
      '.......hSSLLLLLLLLS.....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLL~~LLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOLLSSk....',
      '........hSSSSSSSSk......',
      '........hsssssssh.......',
      '.........SSSSSk.........',
      '.........11111..........',
      '........1133311.........',
      '.......11233332111......',
      '......112222222211......',
      '.....11222222222211.....',
      '....1122222333222211....',
      '....122222233332221.....',
      '....122222333332221.....',
      '....122223333322221.....',
      '....122222222222221.....',
      '....122222222222221.....',
      '....122222222222221.....',
      '....111111111111111.....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........kkhhhhhhhk...',
      '..........kkhhgggggHhk..',
      '..........khgggsssssHk..',
      '..........khssSSSSSSsk..',
      '.........khsSLLLLLLSSk..',
      '........kSSLL~~~~LLSSk..',
      '........hSSLLLLLLLLSSk..',
      '........hSSLLLLLLLLSSk..',
      '........hSSLLLeeLLLSSk..',
      '........hSSLLqqqqLLSSk..',
      '........hSSLLqqqqLLSSk..',
      '.........hSSSSSSSSSSk...',
      '..........hsssssssh.....',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
    ],
  },
  connor: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........kkkkkkkkk.......',
      '........kssssssss.......',
      '.......khSSSSSSSSk......',
      '.......khSLLLLLLLSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hSSSSSSSSh......',
      '.........SSSSk..........',
      '........yyyyyyyy........',
      '.......yy##yy##yyy......',
      '......yyyyyyyyyyyyy.....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........kkkkkkkkk....',
      '...........kssssssss....',
      '..........khSSSSSSSSk...',
      '..........khSLLLLLLLSk..',
      '..........hSSLLLLLLLSk..',
      '.........hSSLL~~LLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSh....',
      '..........yyyyyyyy......',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
  doherty: {
    upright: [
      '........................',
      '........................',
      '..........GGGG..........',
      '.........GggggG.........',
      '........GgggggggG.......',
      '........GgggggggG.......',
      '........#gggggg#........',
      '........#sssssss#.......',
      '.......ksSSSSSSSSk......',
      '.......ksSLL~LLLLSk.....',
      '.......ksSLLLLLLLSk.....',
      '.......ksSLwewewLSk.....',
      '.......ksSLLLLLLLSk.....',
      '.......ksSLLLeLLLSk.....',
      '.......ksSLL~~LLLSk.....',
      '.......ksSLLOOLLLSk.....',
      '........kSSSSSSSSk......',
      '........hssssssh........',
      '.........SSSSk..........',
      '........8EEEEEEE8.......',
      '.......889999999988.....',
      '......88999999999988....',
      '.....88999EEEEEE99988...',
      '....88999EEEEEEEE99988..',
      '....899EEEEEEEEEEEE998..',
      '....8999EEEEEEEEEE9998..',
      '....89999EEEEEEEE99998..',
      '....899999EEEEEE999998..',
      '....8999999999999999998.',
      '....8888888888888888888.',
      '........................',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '..............GGGG......',
      '............GgggggG.....',
      '...........GggggggggG...',
      '...........#gggggg#.....',
      '...........#sssssss#....',
      '..........ksSSSSSSSSk...',
      '.........ksSLL~~LLLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLeeLLSk...',
      '.........ksSLLqqqqLSk...',
      '..........ksSSSSSSSk....',
      '...........hsssssh......',
      '..........WWWWWWWWW.....',
      '.........WWWWWWWWWWW....',
      '........WWWWWWWWWWWWW...',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WYWYWYWYWYWYWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
  jake: {
    upright: [
      '........................',
      '........................',
      '.........hhh.hhh........',
      '........hhhhkhhhk.......',
      '.......kWWWWWWWWWk......',
      '.......kWWzzzWWWWk......',
      '.......kWWzzzzzWWk......',
      '.......kWWWWWWWWWk......',
      '.......khSSSSSSSSk......',
      '.......khSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOLLSk.....',
      '........hSSSSSSSSh......',
      '.......ccccccccccc......',
      '......cccccccccccc......',
      '......cdddddddddddc.....',
      '.......kkkkkkkkk........',
      '......kkkk...kkkkkk.....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkzzkkkkkkk....',
      '.....kkkkkkzzzkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '.....kkkkkkkkkkkkkkk....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhh.hhh.....',
      '...........hhhhkhhhk....',
      '..........kWWWWWWWWWk...',
      '..........kWWzzzWWWWk...',
      '..........kWWzzzzzWWk...',
      '..........kWWWWWWWWWk...',
      '..........khSSSSSSSSk...',
      '.........khSLL~~LLSSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSh....',
      '.........ccccccccccc....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWzzWWWWWWWWW..',
      '.....WWWWWWzzzWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
  joan: {
    upright: [
      '........................',
      '........................',
      '.........GGGGGG.........',
      '........GGggggGGG.......',
      '.......GgggggggggG......',
      '.......#gggggg#.........',
      '.......#sssssss#........',
      '......ksSSSSSSSSk.......',
      '......ksSLLLLLLLSk......',
      '......ksSLwewewLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSL~~~LLLSk......',
      '......ksSLLLeLLLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSLLOOOLLSk......',
      '.......hsssssssh........',
      '........SSSSk...........',
      '.......vVVVVVVVv........',
      '......vVVVVVVVVVv.......',
      '.....vVVVVVVVVVVVv......',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVV##V####VVVVv.....',
      '....vVVV##VV####VVv.....',
      '....vVVV#VV###VVVVv.....',
      '....vVVVV#####VVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vVVVVVVVVVVVVVv.....',
      '....vvvvvvvvvvvvvvv.....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '..............GGGGGG....',
      '............GGggggGGG...',
      '...........GgggggggggG..',
      '...........#gggggg#.....',
      '...........#sssssss#....',
      '..........ksSSSSSSSSk...',
      '..........ksSLL~~LLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLLLLLSk...',
      '.........ksSLLLeeLLSk...',
      '.........ksSLqqqqqLSk...',
      '..........ksSSSSSSSk....',
      '...........hsssssh......',
      '..........WWWWWWWWW.....',
      '.........WWWWWWWWWWW....',
      '........WWWWWWWWWWWWW...',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WYWYWYWYWYWYWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '.......WWWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
  leo: {
    upright: [
      '........................',
      '........................',
      '........................',
      '........................',
      '..........hhhh..........',
      '.........hHHHHhh........',
      '........hhHHHHHHh.......',
      '........hhssssssh.......',
      '........hSSSSSSSk.......',
      '.......hSSLLLLLLSk......',
      '.......hSSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOLLSk.....',
      '........hSSSSSSSk.......',
      '.........hssssh.........',
      '..........SSSk..........',
      '.........VVVVVV.........',
      '........VVVVVVVVV.......',
      '.......VVVVViVVVVVV.....',
      '......VVViVVVVVViVVV....',
      '......VVVVVVVVVVVVVV....',
      '......VVVVViVVVVVVVV....',
      '......VVVVVVVVVViVVV....',
      '......VVViVVVVVVVVVV....',
      '......VVVVVVVVVVVVVV....',
      '......VVVVVVVVVVVVVV....',
      '.......BB........BB.....',
      '.......BB........BB.....',
      '........................',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '..............hhhh......',
      '............hHHHHhh.....',
      '...........hhHHHHHHh....',
      '..........hhssssssh.....',
      '..........hSSSSSSSk.....',
      '..........hSSLLLLLSk....',
      '.........hSSL~~~~LSk....',
      '.........hSSLLLLLLSk....',
      '.........hSSLLLeeLSk....',
      '.........hSSLqqqLLSk....',
      '..........hSSSSSSSk.....',
      '...........hssssh.......',
      '..........VVVVVVVV......',
      '.........VVVVViVVVV.....',
      '.........WWWWWWWWWW.....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WYWYWYWYWYWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '........WWWWWWWWWWWW....',
      '.........WWWWWWWWWW.....',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  liam: {
    upright: [
      '........................',
      '........................',
      '.........hhhhhhh........',
      '........hhhHHhhhh.......',
      '.......khhHHHHhhhh......',
      '.......khhhsssssH.......',
      '.......khssSSSSSSk......',
      '.......khSSLLLLLSk......',
      '.......hSSLwewewLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLLeLLLSk.....',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLLOOOOLSk.....',
      '........hsssssssh.......',
      '........kkkkkkkk........',
      '.........SSSSk..........',
      '........kkkkkkkk........',
      '.......kkkkkkkkkkk......',
      '......kkkkkkkkkkkkk.....',
      '.....kkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkkk...',
      '....kkSSkkkkkkkkSSkk....',
      '....kkSSSSkkkkSSSSkk....',
      '....kkkSSSSSSSSSSkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '....kkkkkkkkkkkkkkkk....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhhhhhh.....',
      '...........hhhHHhhhh....',
      '..........khhHHHHhhhh...',
      '..........khhhsssssH....',
      '..........khssSSSSSSk...',
      '..........khSSLLLLLSk...',
      '.........hSSLL~~LLSSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hsssssssh.....',
      '..........kkkkkkkkk.....',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
  marcus: {
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........kkkkkkkkk....',
      '...........kkkkkkkkk....',
      '..........kkssssssssk...',
      '..........khSSSSSSSSk...',
      '..........hSSLLLLLLLSk..',
      '.........hSSLL~~LLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSh....',
      '..........WWWWWWWW......',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWzzzWWWWWWWWW...',
      '.....WWzzzzzzzWWWWWWW...',
      '.....WzzzzzzzzzWWWWWW...',
      '.....WzzzzzzzzzWWWWWW...',
      '.....WWzzzzzzzWWWWWWW...',
      '.....WWWzzzzzWWWWWWWW...',
      '.....WWWWzzzWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
  maya: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........khhhhhhhhk......',
      '........khhhhhhhhk......',
      '........khhsssssHk......',
      '........khsSSSSSSk......',
      '........khSLLLLLSk......',
      '.......khSLwewewLSk.....',
      '.......khSL~~~~~LSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOLLLSk....',
      '........hSSSSSSSSk......',
      '.........hssssh.........',
      '.........SSSSk..........',
      '........yyyyyyyy........',
      '.......yy##yy##yyy......',
      '......yyyyyyyyyyyyy.....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyy#####yyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '.....yyyyyyyyyyyyyyy....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........khhhhhhhhk...',
      '..........khhhhhhhhhk...',
      '..........khhssssssHk...',
      '..........khsSSSSSSSk...',
      '..........khSLL~~LLSk...',
      '.........khSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqqLSk...',
      '..........hSSSSSSSSk....',
      '...........hssssssh.....',
      '..........WWWWWWWWWW....',
      '.........WWWWWWWWWWWW...',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WYWYWYWYWYWYWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '.........WWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  ravi: {
    upright: [
      '........................',
      '........................',
      '.........kkkkkkk........',
      '........khhgggggk.......',
      '........khhgggggk.......',
      '........khggsssss.......',
      '........khssSSSSSk......',
      '.......khSSLLLLLSk......',
      '.......khSLwewewLSk.....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLL~~LLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLTLLLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hsssssssh.......',
      '........tttttttttt......',
      '.........SSSSk..........',
      '.........hhhhh..........',
      '........hHHHHHHh........',
      '.......hHWWWWWWWHh......',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHWWWWWWWWWHh.....',
      '......hHHHHHHHHHHHHh....',
      '......hhhhhhhhhhhhhh....',
      '......hhhhhhhhhhhhhh....',
      '......hhhhhhhhhhhhhh....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkkkkk.....',
      '...........khhgggggk....',
      '..........khhgggggk.....',
      '..........khggsssss.....',
      '..........khssSSSSSk....',
      '.........khSSLLLLLSk....',
      '.........khSL~~~~LSk....',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLLqqqLLSk...',
      '..........hssssssssh....',
      '..........WWWWWWWWWW....',
      '.........WWWWWWWWWWWW...',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WYWYWYWYWYWYWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '........WWWWWWWWWWWWWW..',
      '.........WWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  ruby: {
    upright: [
      '........................',
      '........................',
      '........................',
      '..........kkkk..........',
      '.........khhhhhk........',
      '........khhhHHhhk.......',
      '........khhHHHHhk7......',
      '.......khhsssssHk7......',
      '.......kSSSSSSSSk.......',
      '.......kSLLLLLLLSk......',
      '......ksSLwewewLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSLLLeLLLSk......',
      '......ksSLLLLLLLSk......',
      '......ksSSLOOLSSk.......',
      '.......kssssssh.........',
      '.........SSSk...........',
      '........466666664.......',
      '.......455555555554.....',
      '......4555X555X5555.....',
      '.....455555X5555555.....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....4555555X5555554....',
      '.....44444444444444.....',
      '......WWW......WWW......',
      '.....WWWW......WWWW.....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............kkkk........',
      '...........khhhhhk......',
      '..........khhhHHhhk.....',
      '..........khhHHHHhk.....',
      '.........khhsssssHk.....',
      '.........kSSSSSSSSk.....',
      '.........kSLL~~LLSk.....',
      '........ksSLLLLLLSk.....',
      '........ksSLLeeLLSk.....',
      '........ksSLqqqqLSk.....',
      '.........kssssssh.......',
      '.........WWWWWWWW.......',
      '........WWWWWWWWWW......',
      '.......WWWWWWWWWWWW.....',
      '......WWWWWWWWWWWWWW....',
      '......WYWYWYWYWYWYWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWW....',
      '.......WWWWWWWWWWWW.....',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  sarah: {
    upright: [
      '........................',
      '........................',
      '..........hhhh..........',
      '.........hhhhhhk........',
      '........hhhHHhhhhk......',
      '........hhhHHHHhhhk.....',
      '........khhsssssHhk.....',
      '........khSSSSSSSHk.....',
      '.......khSLLLLLLLSHk....',
      '.......khSLwewewLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLLeLLLLSk....',
      '.......hhSLLLLLLLLSk....',
      '.......hhSLLOOLLLLSk....',
      '........hSSSSSSSSk......',
      '.......hhssssssshh......',
      '.......hhhSSSShhhh......',
      '......XXXWWWWWWWXXX.....',
      '.....XXXWWWWWWWWWXXXX...',
      '....XXWWWWWWWWWWWWWXX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XWWWWWWWWWWWWWWWX...',
      '....XYYYWWWWWWWYYYYYX...',
      '....XXXXXXXXXXXXXXXXX...',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhhh........',
      '...........hhhhhhk......',
      '..........hhhHHhhhhk....',
      '..........hhhHHHHhhhk...',
      '..........khhsssssHhk...',
      '..........khSSSSSSSHk...',
      '.........khSLL~~LLLSk...',
      '.........hhSLLLLLLLSk...',
      '.........hhSLLLLLLLSk...',
      '.........hhSLLLeeLLSk...',
      '.........hhSLqqqqLLSk...',
      '..........hSSSSSSSk.....',
      '.........hhsssssshh.....',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWzzzWWWWWWWW..',
      '.....WWWWWzzzzzWWWWWWW..',
      '.....WWWWzzzzzzzWWWWWW..',
      '.....WWWWWzzzzzWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
    ],
  },
  tom: {
    upright: [
      '........................',
      '........................',
      '.........hhhhhhh........',
      '........hHhhhhhHh.......',
      '.......hhHhhgggHhh......',
      '.......khhgggsssHk......',
      '.......khssSSSSSSk......',
      '.......hSSLLLLLLLSk.....',
      '.......hSSLwewewLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLLeLLLLSk....',
      '.......hSSLLLLLLLLSk....',
      '.......hSSLLOOOOLLSk....',
      '........hsssssssh.......',
      '........kkkkkkkkk.......',
      '.........SSSSk..........',
      '.........WWWWW..........',
      '........kWWWWWkk........',
      '.......kkWWWWWWkkk......',
      '......kkkWWWWWWWkkk.....',
      '.....kkkhWWWWWWWhkkk....',
      '.....kkhhWWWWWWWhhkk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkhhhhhhhhhhhhk....',
      '.....kkkkkkkkkkkkkkk....',
      '........................',
    ],
    supine: [
      '........................',
      '........................',
      '............hhhhhhh.....',
      '...........hHhhhhhHh....',
      '..........hhHhhgggHhh...',
      '..........khhgggsssHk...',
      '..........khssSSSSSSk...',
      '..........hSSLLLLLLSk...',
      '.........hSSLL~~LLSSk...',
      '.........hSSLLLLLLLSk...',
      '.........hSSLLLeeLLSk...',
      '.........hSSLqqqqLLSk...',
      '..........hssssssh......',
      '..........kkkkkkkk......',
      '........WWWWWWWWWWW.....',
      '.......WWWWWWWWWWWWW....',
      '......WWWWWWWWWWWWWWW...',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WYWYWYWYWYWYWYWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '.....WWWWWWWWWWWWWWWWW..',
      '......WWWWWWWWWWWWWWW...',
      '........................',
      '........................',
      '........................',
    ],
  },
};

export function extraPatientToSvg(rows: string[], scale = 4): string {
  const w = rows[0]!.length;
  const h = rows.length;
  let svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" ` +
    `shape-rendering="crispEdges" style="image-rendering:pixelated;` +
    `width:${w * scale}px;height:${h * scale}px;display:block">`;
  for (let y = 0; y < h; y++) {
    const row = rows[y]!;
    let x = 0;
    while (x < row.length) {
      const ch = row[x]!;
      const col = EXTRA_PATIENT_PAL[ch];
      if (col == null) {
        x++;
        continue;
      }
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      svg += `<rect x="${x}" y="${y}" width="${end - x}" height="1" fill="${col}"/>`;
      x = end;
    }
  }
  svg += `</svg>`;
  return svg;
}