/**
 * Phase 2 FX sprites (M65) — particles, alerts, and emotes.
 * 16×16 paint-by-string in a self-contained palette. Used for:
 *   - particles: sweat, blood, urticaria flare, etc. (state-change feedback)
 *   - alerts: crash call, pager bleep, pre-alert
 *   - emotes: exclamation, question, sweat, ellipsis, heart_pulse, relief_exhale
 */

const FX_PAL: Record<string, string | null> = {
  '.': null,
  '#': '#1a1310',
  '~': '#3a2a22',
  'A': '#a4d4e8',
  'a': '#e0f0f8',
  'z': '#7A1E16',
  'Z': '#4D110B',
  'R': '#E85045',
  'r': '#C8362A',
  'Y': '#F4C860',
  'y': '#E0A82E',
  'g': '#86E0B5',
  'G': '#5BBF8F',
  't': '#7FCBC8',
  'T': '#4FA3A0',
  'p': '#f29991',
  'P': '#fbbab2',
  'W': '#f4f7f9',
  'w': '#e8e4d8',
  's': '#6B6862',
  'S': '#3a3a3a',
  'c': '#D6D4CD',
  'C': '#9C9A93',
  'b': '#B8D8E8',
  'B': '#7AA8C0',
  'k': '#0d0805',
  'e': '#5BBF8F',
  'E': '#86E0B5',
  'j': '#dcc46a',
  'J': '#f0dc8a',
  'm': '#5a6a8a',
  'M': '#7e8eae'
};

export function fxFrameToSvg(rows: string[], scale = 2): string {
  const w = rows[0]!.length;
  const h = rows.length;
  let svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" ` +
    `shape-rendering="crispEdges" style="image-rendering:pixelated;` +
    `width:${w * scale}px;height:${h * scale}px;display:block">`;
  for (let y = 0; y < h; y++) {
    const row = rows[y]!;
    let x = 0;
    while (x < row.length) {
      const ch = row[x]!;
      const col = FX_PAL[ch];
      if (col == null) {
        x++;
        continue;
      }
      let end = x + 1;
      while (end < row.length && row[end] === ch) end++;
      svg += `<rect x="${x}" y="${y}" width="${end - x}" height="1" fill="${col}"/>`;
      x = end;
    }
  }
  svg += '</svg>';
  return svg;
}

export const FX_PARTICLES: Record<string, string[]> = {
  sweat_drop: [
    '................',
    '......AA........',
    '......AA........',
    '.....AaaA.......',
    '.....AaaA.......',
    '....AaaaaA......',
    '....AaaaaA......',
    '...AaaaaaaA.....',
    '...AaaaaaaA.....',
    '...AaaaaaaA.....',
    '....AaaaaA......',
    '....AAAAA.......',
    '................',
    '................',
    '................',
    '................',
  ],
  blood_splat: [
    '................',
    '......zz........',
    '.....zZZz.......',
    '..z..zZZz..z....',
    '.zZz.zZZz.zZz...',
    '.zZz.ZZZZ.zZz...',
    '..z.zZZZZz.z....',
    '....zZZZZz......',
    '...zZZZZZZz.....',
    '...zZZZZZZz.....',
    '....zZZZZz......',
    '..z..zZZz..z....',
    '.zz..zZZz..zz...',
    '......zz........',
    '................',
    '................',
  ],
  urticaria_flare: [
    '................',
    '.....pPpPp......',
    '....PPPPPPP.....',
    '...pPPRRRPPp....',
    '...PPRRRRRPP....',
    '...PPRRrRRPP....',
    '...PPRRRRRPP....',
    '...pPPRRRPPp....',
    '....PPPPPPP.....',
    '.....pPpPp......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  success_sparkle: [
    '......y.........',
    '......y.........',
    '.....yYy........',
    '....yYYYy.......',
    '..y.YYWWY.y.....',
    '.yYyYWWYYyYy....',
    '..yYYWWYYYy.....',
    '...yYYYYYy......',
    '....yYYYy.......',
    '.....yYy........',
    '......y.........',
    '......y.........',
    '..y...........y.',
    '..y.....y.....y.',
    '.....y..y.......',
    '.....y..........',
  ],
  defib_bolt: [
    '......eEe.......',
    '.....eEEEe......',
    '....eEEEEEe.....',
    '....eEEEEEe.....',
    '....eEEEEEe.....',
    '......eEe.......',
    '....eeeEeee.....',
    '...eEEEEEEEe....',
    '..eEEEEEEEEEe...',
    '...eEEEEEEEe....',
    '....eeEEEee.....',
    '......eEe.......',
    '......eEe.......',
    '.....eEEEe......',
    '....eEEEEEe.....',
    '......eee.......',
  ],
  vomit_bowl: [
    '................',
    '.CCCCCCCCCCCCCC.',
    '.cBBBBBBBBBBBBc.',
    '.cBjjJJJjJJJJBc.',
    '.cBJJJJJJJJJJBc.',
    '.cBjJJJJJJJJjBc.',
    '..cBJJJJJJJJBc..',
    '..cBJJjjJJJJBc..',
    '...cBJJJJJJBc...',
    '....cBBBBBBc....',
    '.....ccccccs....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  iv_drip: [
    '......##........',
    '......##........',
    '......##........',
    '......##........',
    '......##........',
    '......##........',
    '......AA........',
    '.....AaaA.......',
    '.....AaaA.......',
    '....AaaaaA......',
    '....AAAAA.......',
    '................',
    '......##........',
    '......##........',
    '......##........',
    '......##........',
  ],
  pulse_ring: [
    '......RRRR......',
    '....RR....RR....',
    '...R........R...',
    '..R..........R..',
    '..R...rrrr...R..',
    '.R...r....r...R.',
    '.R..r......r..R.',
    '.R..r......r..R.',
    '.R..r......r..R.',
    '.R..r......r..R.',
    '.R...r....r...R.',
    '..R...rrrr...R..',
    '..R..........R..',
    '...R........R...',
    '....RR....RR....',
    '......RRRR......',
  ],
};

export const FX_ALERTS: Record<string, string[]> = {
  crash_call: [
    '................',
    '..rrrrrrrrrrrr..',
    '..rRRRRRRRRRRr..',
    '..rRZZZZZZZZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZWkkkkWZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZkkkkkkZRr..',
    '..rRZkWkkWkZRr..',
    '..rRZkWkkWkZRr..',
    '..rRZkkkkkkZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZZZZZZZZRr..',
    '..rRRRRRRRRRRr..',
    '..rrrrrrrrrrrr..',
    '................',
  ],
  pager_bleep: [
    '................',
    '...##########...',
    '..#kkkkkkkkkk#..',
    '..#kssssssssk#..',
    '..#ksWWWWWWsk#..',
    '..#ksWkkkkWsk#..',
    '..#ksWkkkkWsk#..',
    '..#ksWWWWWWsk#..',
    '..#kssssssssk#..',
    '..#k##kkkk##k#..',
    '..#k##kkkk##k#..',
    '..#kkkkkkkkkk#..',
    '...##########...',
    '......yyy.......',
    '......yYy.......',
    '......yyy.......',
  ],
  pre_alert_red: [
    '..rrrrrrrrrrrr..',
    '..rRRRRRRRRRRr..',
    '..rRZZZZZZZZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZWkWkWWZRr..',
    '..rRZWkkWWWZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZkWkWkWZRr..',
    '..rRZWkkWWWZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZkkkkkkZRr..',
    '..rRZWWWWWWZRr..',
    '..rRZZZZZZZZRr..',
    '..rRRRRRRRRRRr..',
    '..rrrrrrrrrrrr..',
    '................',
  ],
};

export const FX_EMOTES: Record<string, string[]> = {
  exclamation: [
    '......RRRR......',
    '.....RRRRRR.....',
    '....RRRWWWRR....',
    '...RRRWWWWWRR...',
    '...RRWWkkWWRR...',
    '...RRWWkkWWRR...',
    '...RRWWkkWWRR...',
    '...RRWWkkWWRR...',
    '...RRWWWWWWRR...',
    '...RRRWWWWRRR...',
    '....RRWWkWRRR...',
    '.....RWkkWR.....',
    '......RWWR......',
    '.......RR.......',
    '......RR........',
    '.....RR.........',
  ],
  question: [
    '......yyyy......',
    '....yyYYYYyy....',
    '...yYYWWWWYYy...',
    '..yYYWWkkWWYYy..',
    '..yYWWkWWWkYWy..',
    '..yYYYYYWWkYYy..',
    '...yyYYYWWkYy...',
    '......yYWWk.....',
    '.....yYWWk......',
    '.....yYWWY......',
    '.....yYYYy......',
    '......yyy.......',
    '................',
    '......yYy.......',
    '......yYy.......',
    '.......y........',
  ],
  sweat: [
    '...AA...........',
    '..AaaA..........',
    '..AaaA..........',
    '.AaaaaA.........',
    '.AaaaaA.........',
    'AaaaaaaA........',
    '.AAAAAAA........',
    '................',
    '...........AA...',
    '..........AaaA..',
    '..........AaaA..',
    '.........AaaaaA.',
    '.........AAAAA..',
    '................',
    '................',
    '................',
  ],
  ellipsis: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....SSS.........',
    '....SsS.........',
    '....SSS.........',
    '........SSS.....',
    '........SsS.....',
    '........SSS.....',
    '............SSS.',
    '............SsS.',
    '............SSS.',
    '................',
    '................',
  ],
  heart_pulse: [
    '................',
    '...RR....RR.....',
    '..RRRR..RRRR....',
    '.RRRRRRRRRRRR...',
    '.RRRRRRRRRRRR...',
    '.RRRRRRRRRRRR...',
    '..RRRRRRRRRR....',
    '...RRRRRRRR.....',
    '....RRRRRR......',
    '.....RRRR.......',
    '......RR........',
    '................',
    '...gggg.........',
    '.gg....gggggg...',
    'g........g..gg..',
    '............ggg.',
  ],
  relief_exhale: [
    '................',
    '................',
    '....aaaaaa......',
    '...aAAAAaaAaa...',
    '...aaaaaaaaaaa..',
    '....aaaaaa..a...',
    '......aaa.......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};
