/**
 * F1 doctor walk cycle (M65). 4-direction × 4-frame standard.
 * Currently authored frames: f1_down_F0 (stand), f1_down_F1 (step L),
 * f1_down_F3 (step R), f1_right_F0 (side stance).
 *
 * Per the design drop: F2/F1_up frames re-use F0 to save animation
 * memory — that pattern is preserved at the consumption site.
 * 16×24 base; the renderer uses the existing NPC palette.
 */

export const WALK_FRAMES: Record<string, string[]> = {
  'f1_down_F0': [
    '................',
    '......####......',
    '.....#kkkk#.....',
    '.....#kkkk#.....',
    '.....#sSSs#.....',
    '.....#sees#.....',
    '.....#sSSSs.....',
    '.....#sLmLs.....',
    '......#ss#......',
    '....cCttttCc....',
    '...cCCttttCCc...',
    '...cCCtiiitCCc..',
    '...cCCtiIitCCc..',
    '...cCCttttCCc...',
    '...cCCttttCCc...',
    '...cCCttZttCCc..',
    '...cCCttttCCc...',
    '....cdttttdc....',
    '.....tttttt.....',
    '.....tttttt.....',
    '.....tttttt.....',
    '.....tttttt.....',
    '....fFF##FFf....',
    '....fFf..fFf....',
  ],
  'f1_down_F1': [
    '................',
    '......####......',
    '.....#kkkk#.....',
    '.....#kkkk#.....',
    '.....#sSSs#.....',
    '.....#sees#.....',
    '.....#sSSSs.....',
    '.....#sLmLs.....',
    '.....#ss#.......',
    '....cCttttCc....',
    '...cCCttttCCc...',
    '..cCCCtiiitCCc..',
    '..cCCCtiIitCCc..',
    '..cCCCttttCCc...',
    '...cCCttttCCc...',
    '...cCCttZttCCc..',
    '...cCCttttCCc...',
    '....cdttttdc....',
    '.....tttttt.....',
    '.....tttttt.....',
    '.....tttttt.....',
    '....ttttt.......',
    '...fFF##.fFf....',
    '...fFf...fFf....',
  ],
  'f1_down_F3': [
    '................',
    '......####......',
    '.....#kkkk#.....',
    '.....#kkkk#.....',
    '.....#sSSs#.....',
    '.....#sees#.....',
    '.....#sSSSs.....',
    '.....#sLmLs.....',
    '.......#ss#.....',
    '....cCttttCc....',
    '...cCCttttCCc...',
    '...cCCtiiitCCcc.',
    '...cCCtiIitCCcc.',
    '...cCCttttCCcc..',
    '...cCCttttCCc...',
    '...cCCttZttCCc..',
    '...cCCttttCCc...',
    '....cdttttdc....',
    '.....tttttt.....',
    '.....tttttt.....',
    '.....tttttt.....',
    '.......ttttt....',
    '....fFf.fFF##...',
    '....fFf...fFf...',
  ],
  'f1_right_F0': [
    '................',
    '.......####.....',
    '......#kkkk#....',
    '......#kkkks....',
    '......#sSSs#....',
    '......#sse>#....',
    '......#sSSs#....',
    '......#sLms#....',
    '.......#ss#.....',
    '....ccCttttCc...',
    '...ccCCttttCC...',
    '...ccCCtiitCC...',
    '...ccCCtiItCC...',
    '....cCCttttCC...',
    '....cCCttttCC...',
    '....cCCttZttC...',
    '....cCCttttCC...',
    '.....cdttttdc...',
    '......tttttt....',
    '......tttttt....',
    '......tttttt....',
    '......tttttt....',
    '......fFF##F....',
    '......fFf.fF....',
  ]
};
