/**
 * Environment tiles — lino floor, teal walls, curtain, trolley,
 * drip stand, wall monitor, hand-gel pump, sharps bin.
 *
 * Ported from Claude Design's `world-sprites.js` (second drop).
 * Each tile is 16×16 paint-by-string in the shared world palette
 * (PROP_PAL — colocated with propSprites.ts since the chars and
 * meanings match).
 *
 * As of M46 these tiles are *parked* — not wired into gameplay.
 * They exist so a future overworld pass can compose ED bays from
 * them without re-authoring the silhouettes.
 *
 * The minimal Visual Style Guide screen
 * (src/ui/styleguide/AssetLibraryScreen.tsx) imports these so design
 * can see them in-app via the ?style-guide=1 URL gate.
 */

import { propFrameToSvg } from './propSprites';

export const WORLD_TILES: Record<string, string[]> = {
  lino_floor: [
    'llllllllllllllll',
    'lllllLllllllllll',
    'lllllllllllLllll',
    'lLllllllllllllll',
    'llllllllLlllllll',
    'lllllllllllllLll',
    'llLlllllllllllll',
    'lllllllllllllllL',
    'llllllLlllllllll',
    'lllllllllllllllL',
    'llllllllllLlllll',
    'lLllllllllllllll',
    'llllllllllllllll',
    'lllllLllllllllll',
    'llllllllLlllllll',
    'llllllllllllllll',
  ],
  lino_scuff: [
    'lLllllLlllllllll',
    'lllllllllllLllll',
    'lLLLLLllllllllll',
    'llLLLlllllllllll',
    'llLLlllllllllLll',
    'llllllllLLllllll',
    'lllllllLLLlllLll',
    'llllllllLlllllLl',
    'llllllllLLllllll',
    'lLllllllllllllll',
    'lllllllLLlllllll',
    'lllllLllllllllll',
    'llllllllllllllLl',
    'lllLllllllllllll',
    'lllLLlllllllllll',
    'llllllllllllllll',
  ],
  wall_teal: [
    'TTTTTTTTTTTTTTTT',
    'TuTTTuTTTuTTTuTT',
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'TTuTTTTuTTTuTTTu',
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'TuTTTTuTTTTuTTTT',
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'TTTuTTTuTTTuTTTu',
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'TuTTTuTTTuTTTuTT',
    'TTTTTTTTTTTTTTTT',
    'uuuuuuuuuuuuuuuu',
  ],
  wall_resus_stripe: [
    'TTTTTTTTTTTTTTTT',
    'TuTTTuTTTuTTTuTT',
    'TTTTTTTTTTTTTTTT',
    'RRRRRRRRRRRRRRRR',
    'rrrrrrrrrrrrrrrr',
    'RRRRRRRRRRRRRRRR',
    'TTTTTTTTTTTTTTTT',
    'TuTTTuTTTuTTTuTT',
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'TTTuTTTuTTTuTTTu',
    'TTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTT',
    'TuTTTuTTTuTTTuTT',
    'TTTTTTTTTTTTTTTT',
    'uuuuuuuuuuuuuuuu',
  ],
  curtain: [
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
    'TuTuTuTuTuTuTuTu',
  ],
  trolley_empty: [
    '................',
    '..############..',
    '..#WWWWWWWWWW#..',
    '..#WWWWWWWWWW#..',
    '..#WWWWWWWWWW#..',
    '..#WWWWWWWWWW#..',
    '..############..',
    '...##........##.',
    '....##........##',
    '....##........##',
    '....##........##',
    '....##........##',
    '....##........##',
    '...ssss......sss',
    '...ssss......sss',
    '................',
  ],
  trolley_occupied: [
    '................',
    '..############..',
    '..#WWWWWWWWWW#..',
    '..#WWWhhhhWWW#..',
    '..#WWhHHHHhWW#..',
    '..#WhHHHHHHhW#..',
    '..############..',
    '...##........##.',
    '....##........##',
    '....##........##',
    '....##........##',
    '....##........##',
    '....##........##',
    '...ssss......sss',
    '...ssss......sss',
    '................',
  ],
  drip_stand: [
    '......CCCC......',
    '.....CsCsC......',
    '....CCCCCCC.....',
    '....CibbbiC.....',
    '....CibIbiC.....',
    '....CibbbiC.....',
    '....CibbbiC.....',
    '....CCCCCCC.....',
    '......##........',
    '......##........',
    '......##........',
    '......##........',
    '......##........',
    '......##........',
    '.....####.......',
    '.....####.......',
  ],
  monitor_wall: [
    '................',
    '..############..',
    '..#wwwwwwwwww#..',
    '..#wggggggggw#..',
    '..#wgrgrgrgw#w..',
    '..#wggggggggw#..',
    '..#wggGGGGggw#..',
    '..#wggggggggw#..',
    '..#wwwwwwwwww#..',
    '..############..',
    '......####......',
    '......####......',
    '......####......',
    '......####......',
    '......####......',
    '................',
  ],
  handgel: [
    '......CCCC......',
    '.....CCCCCC.....',
    '....CCCCCCCC....',
    '....CggggggC....',
    '....CggIggIC....',
    '....CggggggC....',
    '....CggggggC....',
    '....CCCCCCCC....',
    '......####......',
    '......####......',
    '......####......',
    '......####......',
    '......####......',
    '.....######.....',
    '.....######.....',
    '................',
  ],
  sharps_bin: [
    '................',
    '..jjjjjjjjjjjj..',
    '..jJJJJJJJJJJj..',
    '..jJWWWWWWWWJj..',
    '..jJWkkkkkkWJj..',
    '..jJWkkkkkkWJj..',
    '..jJWWWWWWWWJj..',
    '..jJJJJJJJJJJj..',
    '..jJJJJJJJJJJj..',
    '..jJJJJJJJJJJj..',
    '..jJJJJJJJJJJj..',
    '..jJJJJJJJJJJj..',
    '..jJJJJJJJJJJj..',
    '..jjjjjjjjjjjj..',
    '...ssssssssss...',
    '................',
  ],
};

/** Re-export the prop renderer — the world palette is shared. */
export const worldFrameToSvg = propFrameToSvg;
