#!/usr/bin/env tsx
/**
 * scripts/new-episode.ts
 *
 * Generate an Episode YAML skeleton wrapping one or more existing cases.
 *
 * Usage:
 *   pnpm new-episode --id ep_my_shift --title "My shift" \
 *                    --focus case_a,case_b [--ambient case_c] \
 *                    [--arc arc_x] [--duration 20]
 *
 *   pnpm new-episode --list-cases
 *
 * The script verifies referenced cases/arcs exist on disk before
 * writing. The resulting episode is pre-populated with one
 * scheduled `deterioration_if_not_x_by_t` event per focus case at
 * T+5, which the author can edit or delete.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';
import { execSync } from 'node:child_process';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const GREEN = '\x1b[32m';
const DIM = '\x1b[2m';
const RESET = '\x1b[0m';

interface CliArgs {
  id?: string;
  title?: string;
  focus: string[];
  ambient: string[];
  arc: string[];
  duration: number;
  difficulty: string;
  listCases: boolean;
  help: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const out: CliArgs = {
    focus: [],
    ambient: [],
    arc: [],
    duration: 20,
    difficulty: 'CT2',
    listCases: false,
    help: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === '--id') out.id = argv[++i];
    else if (a === '--title') out.title = argv[++i];
    else if (a === '--focus') out.focus = (argv[++i] ?? '').split(',').filter(Boolean);
    else if (a === '--ambient') out.ambient = (argv[++i] ?? '').split(',').filter(Boolean);
    else if (a === '--arc') out.arc = (argv[++i] ?? '').split(',').filter(Boolean);
    else if (a === '--duration') out.duration = Number(argv[++i] ?? out.duration);
    else if (a === '--difficulty') out.difficulty = argv[++i] ?? out.difficulty;
    else if (a === '--list-cases') out.listCases = true;
    else if (a === '--help' || a === '-h') out.help = true;
  }
  return out;
}

function printHelp() {
  console.log(`${GREEN}new-episode${RESET} — author an Episode YAML skeleton`);
  console.log('');
  console.log('Usage:');
  console.log('  pnpm new-episode --id <ep_id> --title <str> --focus <case_a,case_b>');
  console.log('                  [--ambient <case_c>] [--arc <arc_id>]');
  console.log('                  [--duration 20] [--difficulty CT2]');
  console.log('  pnpm new-episode --list-cases');
}

function listExistingIds(dir: string, prefix: string): string[] {
  const out: string[] = [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const f of entries) {
    if (!f.endsWith('.yaml') && !f.endsWith('.yml')) continue;
    try {
      const raw = parseYaml(readFileSync(join(dir, f), 'utf8')) as { id?: string };
      if (typeof raw.id === 'string' && raw.id.startsWith(prefix)) out.push(raw.id);
    } catch {
      // ignore unparseable files; the validator catches them
    }
  }
  return out;
}

function loadTopicTags(caseIds: string[]): string[] {
  const tags = new Set<string>();
  for (const id of caseIds) {
    const path = join(repoRoot, 'content', 'cases', `${id}.yaml`);
    try {
      const raw = parseYaml(readFileSync(path, 'utf8')) as { curriculum_tags?: string[] };
      for (const t of raw.curriculum_tags ?? []) tags.add(t);
    } catch {
      // ignore — validator will warn
    }
  }
  return [...tags];
}

function escapeYaml(s: string): string {
  return s.replace(/'/g, "''");
}

function renderEpisode(args: CliArgs): { episodeId: string; yaml: string } {
  const episodeId = args.id!;
  const title = args.title ?? 'TODO: shift title';
  const focusList = args.focus.map((id) => `  - ${id}`).join('\n');
  const ambientList =
    args.ambient.length > 0 ? args.ambient.map((id) => `  - ${id}`).join('\n') : '  []';
  const arcList = args.arc.length > 0 ? args.arc.map((id) => `  - ${id}`).join('\n') : '  []';

  const eventBlocks = args.focus
    .map(
      (id, i) => `  - id: ev_${id}_deterioration
    type: deterioration_if_not_x_by_t
    t_min: ${5 + i * 4}
    case_id: ${id}
    required_action_ids:
      - mx_TODO  # TODO: management action id whose absence triggers the deterioration
    new_state: arrested # or 'deteriorating'`,
    )
    .join('\n\n');

  const tags = loadTopicTags(args.focus);
  const tagsLine = tags.length > 0 ? `[${tags.join(', ')}]` : '[]  # TODO: at least one';

  return {
    episodeId,
    yaml: `# TODO: SKELETON — author this episode.
#
# Generated by scripts/new-episode.ts on ${new Date().toISOString().slice(0, 10)}.

schema_version: 1
id: ${episodeId}
title: '${escapeYaml(title)}'
learning_objectives:
  - 'TODO: learning objective 1'
  - 'TODO: learning objective 2'

curriculum_tags: ${tagsLine}
difficulty_band: ${args.difficulty}
shift_duration_min: ${args.duration}

focus_cases:
${focusList || '  - case_TODO'}

ambient_cases:
${ambientList}

scheduled_events:
${eventBlocks || '  []'}

arcs:
${arcList}

author_notes: |
  Skeleton — fill in event ids, replace mx_TODO with real action ids
  from the referenced cases, and add narrative ambient pressure where
  appropriate.
`,
  };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    printHelp();
    process.exit(0);
  }
  if (args.listCases) {
    const ids = listExistingIds(join(repoRoot, 'content', 'cases'), 'case_');
    for (const id of ids) console.log(id);
    process.exit(0);
  }
  if (!args.id || args.focus.length === 0) {
    console.error(`${RED}✗${RESET} --id and --focus are required.`);
    printHelp();
    process.exit(1);
  }
  if (!args.id.startsWith('ep_')) {
    console.error(`${RED}✗${RESET} episode id must start with "ep_" (got "${args.id}").`);
    process.exit(1);
  }

  // Resolve referenced ids
  const knownCases = new Set(listExistingIds(join(repoRoot, 'content', 'cases'), 'case_'));
  const knownArcs = new Set(listExistingIds(join(repoRoot, 'content', 'arcs'), 'arc_'));
  const missingCases = [...args.focus, ...args.ambient].filter((id) => !knownCases.has(id));
  const missingArcs = args.arc.filter((id) => !knownArcs.has(id));
  if (missingCases.length > 0) {
    console.error(`${RED}✗${RESET} cases not found: ${missingCases.join(', ')}`);
    console.error(`${DIM}Use --list-cases to see existing ids.${RESET}`);
    process.exit(1);
  }
  if (missingArcs.length > 0) {
    console.error(`${RED}✗${RESET} arcs not found: ${missingArcs.join(', ')}`);
    process.exit(1);
  }

  const { episodeId, yaml } = renderEpisode(args);
  const outPath = join(repoRoot, 'content', 'episodes', `${episodeId}.yaml`);
  if (existsSync(outPath)) {
    console.error(`${RED}✗${RESET} ${outPath} already exists.`);
    process.exit(1);
  }
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, yaml, 'utf8');
  console.log(`${GREEN}✓${RESET} wrote ${outPath}`);
  console.log(`${YELLOW}!${RESET} edit the placeholder action ids before validating.`);

  try {
    execSync('npm run validate-content', { cwd: repoRoot, stdio: 'inherit' });
  } catch {
    console.error(`${YELLOW}!${RESET} Validator surfaced issues — expected for a fresh skeleton.`);
  }
}

main();
